### ISSUE TITLE
Enable WordPress-level backups on docs sites

### ISSUE THREAD

**Issue by supertassu** [jquery/infrastructure-puppet#23]
Even though those can be re-built in case something goes wrong, let's enable Tarsnap backups of the WordPress databases and content so that we have a faster way to recover from a failed WordPress upgrade or similar issue.

**Comment by supertassu** [comment]
Implemented database backups in https://github.com/jquery/infrastructure-puppet/commit/a1b6565d33d32330e05c11d704ae10d03a91b751. Not sure if we need `wp-content/uploads` too if the primary risk we're trying to protect against is a database schema upgrade going wrong.

**Comment by Krinkle** [comment]
@supertassu Not for wpdocs indeed, only for wpblogs.

**Comment by supertassu** [comment]
Thanks for confirming! I'll close this one then, as the blogs sites already have backups for both the databases and uploaded files.
