### ISSUE TITLE
Audit use of npm_dev=>true

### ISSUE THREAD

**Issue by Krinkle** [jquery/infrastructure-puppet#83]
Until today, the `jquery::gitclone` resource used `npm install` plainly upon clone and upon updates.

I've switched it to use `--production` by default, and opted out the existing uses via a new `npm_dev => true` option to make sure anything that might have been relying on that keeps working.

There is is typically 100x more dependencies being downloaded and executed when dev mode is used, so it's worth turning off and reducing risk that way.

Audit and explain or remove `npm_dev => true` from:

* [x] cla.pp: jquery/jquery-license.git
* [x] gruntjscom.pp: gruntjs/gruntjs.com.git
* [x] siteupdater.pp
* [x] swarm.pp: testswarm-browserstack

Follow-up from https://github.com/jquery/infrastructure/issues/526.

**Comment by supertassu** [comment]
For gruntjs there's https://github.com/gruntjs/gruntjs.com/issues/221. Everything else is fixed on the new infrastructure.
